version: '3.0'
services:
  db:
    image: mongo:4.4
  dbgui:
    image: mongo-express:1.0.2
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_BASICAUTH_USERNAME=forster
      - ME_CONFIG_BASICAUTH_PASSWORD=gOU89tRF05
  iam:
    image: quay.io/keycloak/keycloak:23.0.7
    ports:
      - 8080:8080
    environment:
      - KEYCLOAK_ADMIN=forster
      - KEYCLOAK_ADMIN_PASSWORD=4AFXbm5vX7YFjN0rMYKK
    command: start-dev
  mom:
    image: rabbitmq:3.13-management
    ports:
      - 15672:15672
      - 5672:5672
  books:
    image: demoeditor/books-api:0.1
    build:
      context: ./books-controller
      dockerfile: Dockerfile
    ports:
      - 81:8080
    restart: unless-stopped
    healthcheck:
      test: curl http://localhost:8080/status
      interval: 10s
      retries: 3
      start_period: 5s
      timeout: 1s
  authors:
    image: demoeditor/authors-api:0.1
    build:
      context: ./authors-controller
      dockerfile: Dockerfile
    ports:
      - 81:8080
    restart: unless-stopped
    healthcheck:
      test: curl http://localhost:8080/status
      interval: 10s
      retries: 3
      start_period: 5s
      timeout: 1s