version: '3.0'
services:
  db:
    image: mongo:4.4
    networks:
      - back
  dbgui:
    image: mongo-express:1.0.2
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_BASICAUTH_USERNAME=forster
      - ME_CONFIG_BASICAUTH_PASSWORD=gOU89tRF05
      - ME_CONFIG_MONGODB_SERVER=db
    networks:
      - back
  iam:
    image: quay.io/keycloak/keycloak:23.0.7
    ports:
      - 8080:8080
    environment:
      - KEYCLOAK_ADMIN=forster
      - KEYCLOAK_ADMIN_PASSWORD=4AFXbm5vX7YFjN0rMYKK
    command: start-dev
    networks:
      - front
      - back
  mom:
    image: rabbitmq:3.13-management
    ports:
      - 15672:15672
      - 5672:5672
    networks:
      - back
  books:
    image: demoeditor/books-api:0.1
    build:
      context: ./books-controller
      dockerfile: Dockerfile
    ports:
      - 81:8080
    restart: unless-stopped
    healthcheck:
      test: curl http://localhost:8080/status
      interval: 10s
      retries: 3
      start_period: 5s
      timeout: 1s
    networks:
      - front
      - back
    volumes:
      - test:/tmp/data
  authors:
    image: demoeditor/authors-api:0.1
    build:
      context: ./authors-controller
      dockerfile: Dockerfile
    ports:
      - 82:8080
    restart: unless-stopped
    healthcheck:
      test: curl http://localhost:8080/status
      interval: 10s
      retries: 3
      start_period: 5s
      timeout: 1s
    networks:
      - front
      - back
  portal:
    image: demoeditor/portal-gui:0.1
    build:
      context: ./portal-gui
      dockerfile: Dockerfile
    ports:
      - 88:80
    restart: unless-stopped
    networks:
      - front
  bpm:
    image: docker.n8n.io/n8nio/n8n
    ports:
      - 5678:5678
    networks:
      - back
    volumes:
      - test:/tmp/data
  mail:
    image: mailhog/mailhog
    restart: always
    ports:
      - 1025:1025
      - 8025:8025      
    networks:
      - back
networks:
  front:
  back:
volumes:
  test:
    driver: local