services:
  db:
    image: mongo:4.4
    networks:
      - back
  dbgui:
    image: mongo-express:1.0.2
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_BASICAUTH_USERNAME=forster
      - ME_CONFIG_BASICAUTH_PASSWORD=gOU89tRF05
      - ME_CONFIG_MONGODB_SERVER=db
    networks:
      - back
  iam:
    image: quay.io/keycloak/keycloak:23.0.7
    ports:
      - 8088:8080
    environment:
      - KEYCLOAK_ADMIN=forster
      - KEYCLOAK_ADMIN_PASSWORD=4AFXbm5vX7YFjN0rMYKK
    command: start-dev
    networks:
      - front
      - back
  books:
    image: demoeditor/books-api:0.7
    build:
      context: .
      dockerfile: books-controller/Dockerfile
    environment:
      - RABBITMQ_DEFAULT_USER=rapido
      - RABBITMQ_DEFAULT_PASS=k5rXH6wmBhE2bukfXFsz
    ports:
      - 81:8080
    networks:
      - front
      - back
    volumes:
      - import:/tmp/data
  authors:
    image: demoeditor/authors-api:0.7
    build:
      context: .
      dockerfile: authors-controller/Dockerfile
    ports:
      - 82:8080
    networks:
      - front
      - back
  mo:
    image: demoeditor/middleoffice:0.7
    build:
      context: .
      dockerfile: middleoffice/Dockerfile
    ports:
      - 83:8080
    networks:
      - front
      - back
  users:
    image: demoeditor/users-api:0.7
    build:
      context: .
      dockerfile: users-api/Dockerfile
    ports:
      - 84:8080
    networks:
      - front
      - back
  portal:
    image: demoeditor/portal-gui:0.7
    build:
      context: ./portal-gui
      dockerfile: Dockerfile
    ports:
      - 88:80
    networks:
      - front
  contracts:
    image: demoeditor/contracts:0.7
    build:
      context: ./contracts
      dockerfile: Dockerfile
    environment:
      - RABBITMQ_DEFAULT_USER=rapido
      - RABBITMQ_DEFAULT_PASS=k5rXH6wmBhE2bukfXFsz
      # - EDM_CMIS_URL=http://host.docker.internal:8080/alfresco/api/-default-/public/cmis/versions/1.1/browser
      # - EDM_BASE_FOLDER=/root/DemoEditor/
      # - EDM_CMIS_SERVICEACCOUNT_NAME=admin
      # - EDM_CMIS_SERVICEACCOUNT_PASS=admin
    networks:
      - back
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: on-failure
    stdin_open: true
    tty: true
  mail:
    image: mailhog/mailhog
    restart: on-failure
    ports:
      - 1025:1025
      - 8025:8025      
    networks:
      - back
  mom:
    image: rabbitmq:3.13-management
    environment:
      - RABBITMQ_DEFAULT_USER=rapido
      - RABBITMQ_DEFAULT_PASS=k5rXH6wmBhE2bukfXFsz
    ports:
      - 15672:15672
      - 5673:5672
    networks:
      - back
  bpm:
    image: docker.n8n.io/n8nio/n8n
    ports:
      - 5678:5678
    networks:
      - back
    volumes:
      - import:/tmp/workflow
  brms:
    image: openpolicyagent/opa
    ports:
      - 8181:8181
    command: --server --addr :8181
    networks:
      - back
networks:
  front:
  back:
volumes:
  import:
    driver: local
