version: '3.0'
services:
  db:
    image: mongo:4.4
    networks:
      - back
  books:
    image: demoeditor/books-api:0.1
    build:
      context: ./books-controller
      dockerfile: Dockerfile
    ports:
      - 81:8080
    networks:
      - front
      - back
  authors:
    image: demoeditor/authors-api:0.1
    build:
      context: ./authors-controller
      dockerfile: Dockerfile
    ports:
      - 82:8080
    networks:
      - front
      - back
  portal:
    image: demoeditor/portal-gui:0.1
    build:
      context: ./portal-gui
      dockerfile: Dockerfile
    ports:
      - 88:80
    networks:
      - front
networks:
  front:
  back:
